### ISSUE TITLE
Checking site to W3C and Google Page Insights

### ISSUE THREAD

**Issue by mhartz** [tmpworldwide/tmpworldwide.github.io#10]
I think we should include some non-intrusive preliminary tests to check our code and fix before submitting to QA. These tools are easy to use and really take no time to execute, while providing substantial benefits and information.

The first would be the W3C checker [http://validator.w3.org/](http://validator.w3.org/). Code validation is an easy way to spot small issues that you might have missed without having to examine every element. Things like accessibility issues can easily be identified and fixed without much time wasted.

The second would be testing on Google Page Insights.

Here is the suggested entry into the standards:
Loading time is a major contributing factor to page abandonment. So after completion of a site, each front-end developer should test their site Using the Google Developers PageSpeed Insights web application located at [https://developers.google.com/speed/pagespeed/insights/](https://developers.google.com/speed/pagespeed/insights/). It is as easy as copying and pasting the URL into the text field.

Our desired score should be anything above 70/100, however our absolute lowest score should not fall below 60/100 on both mobile and desktop tests.

While it might not be possible to always achieve a perfect or near-perfect score, we should strive for a site that has the best possible score while maintaining the client requirements. Some issues might be out of our control as front-end developers, but we can take other precautions in order to develop the most efficient site possible.

Let me know if there are any objections in adding these to the standards guide and the code review check list.

**Comment by michaelspellacy** [comment]
I like this. Dwelling on it. :-)

**Comment by scampbell44** [comment]
Great idea! I completely agree.

**Comment by designwebsean** [comment]
Pingdom tools is also great. Gives a different look and more information than Google speed test.  http://tools.pingdom.com/fpt/

**Comment by mhartz** [comment]
Any more input on this? Since a week has past I would like to close this issue.

**Comment by scampbell44** [comment]
I second also including Pingdom in the list of resources for the same reasons stated above.

**Comment by mhartz** [comment]
Ok. I will give the option to use Pingdom as well since a lot of people might not know how to calculate http requests and page load size using dev tools. I will add it to the head of the section with all these since it is a tool that can be used for various testing instead of just page insights.

**Comment by mhartz** [comment]
Closed in ee85c4a9e1669c5c57574c97091762b5942aa843 added as 2.1 and 2.2.
