### ISSUE TITLE
Minifying Code

### ISSUE THREAD

**Issue by mhartz** [tmpworldwide/tmpworldwide.github.io#11]
Proposed changes:

HTML
Do not minify HTML.

CSS
CSS should be minified if saving memory is worth sacrificing readability. Such occasions would include extremely large CSS files, or when minifying the code would push the site size under the designated performance budget and all other optimizations have been exhausted.

Javascript
Javascript should be minified if saving memory is worth sacrificing readability. Such occasions would include extremely large JS files, or when minifying the code would push the site size under the designated performance budget and all other optimizations have been exhausted. Another occasion would include a custom library commonly used on many sites with a solid understanding of how to implement it among all team members.

Third-Party Libraries
All third-party libraries should be minified unless some sort of customization has been made to it and requires readability.

**Comment by michaelspellacy** [comment]
I'm okay with this. I don't feel strong need to minify everything under the sun, but only when situation calls for it.

**Comment by michaelspellacy** [comment]
Also, and this is very interesting to note, it is said that some of our best practices may not always be needed in very near future (or may be harmful) if site is served under HTTP/2. https://mattwilcox.net/web-development/http2-for-front-end-web-developers

Might be worth a mention in our standards to be mindful if site is running under http/2.

**Comment by michaelspellacy** [comment]
@mhartz , if nobody chimes in again over the next few days, I move for adoption. You can assign this to yourself and include in the doc at your leisure if you wish.

**Comment by Brockenstein** [comment]
That's interesting about HTTP/2. Anyway I also agree on the original statements.

**Comment by mhartz** [comment]
I will also add something about SCSS and how it doesn't need to be minified, but minified compiled CSS is fine.

**Comment by mhartz** [comment]
Proposed standard For SCSS:
SCSS should never be minified, but the compiled CSS output should always be minified. Later changes and revisions should only be made to the original SCSS file in order to keep both files in sync.

**Comment by michaelspellacy** [comment]
> > ater changes and revisions should only be made to the original SCSS file in order to keep both files in sync.

So, in regards to custom development, it might be a good idea, depending on the situation, not to include/check-in the compiled CSS. This would force the devloper to only work with Sass, right?.

**Comment by mhartz** [comment]
So:
SCSS should never be minified. If the server has the ability to tie in a CSS Preprocessor, no CSS output file should exist. However, if server-side CSS Preprocessing is not available, all compiled CSS should be minified.

**Comment by scampbell44** [comment]
Yes, I like that statement @mhartz.

**Comment by mhartz** [comment]
Ok so here is the final proposed standard for minification:
HTML
Do not minify HTML.

CSS
CSS should be minified if saving memory is worth sacrificing readability. Such occasions would include extremely large CSS files, or when minifying the code would push the site size under the designated performance budget and all other optimizations have been exhausted.

SCSS
SCSS should never be minified. If the server has the ability to tie in a CSS preprocessor, no CSS output file should exist. However, if server-side CSS preprocessing is not available, all compiled CSS should be minified.

Javascript
Javascript should be minified if saving memory is worth sacrificing readability. Such occasions would include extremely large JS files, or when minifying the code would push the site size under the designated performance budget and all other optimizations have been exhausted. Another occasion would include a custom library commonly used on many sites with a solid understanding of how to implement it among all team members.

Third-Party Libraries
All third-party libraries should be minified unless some sort of customization has been made to it and requires readability.

**Comment by scampbell44** [comment]
Looks great! Perfectly succinct :)

**Comment by stephendelancey** [comment]
I like it

**Comment by Brockenstein** [comment]
@mhartz you rox the sox off of the web standards gods.

**Comment by sbkates** [comment]
I agree with the original statement, and Max made good points too. No points of contention here!

**Comment by michaelspellacy** [comment]
Thumbs up here :+1: 

> > no CSS output file should exist

Thanks for adding that.

**Comment by dfoerst** [comment]
Looks good.
