### ISSUE TITLE
Standard: Feature Detection

### ISSUE THREAD

**Issue by michaelspellacy** [tmpworldwide/tmpworldwide.github.io#2]
Touch upon dangers of browser detection and importance of feature detection (duh)

**Comment by sethlopezme** [comment]
Feature detection, FTW

**Comment by michaelspellacy** [comment]
:-) I miss ya here.

**Comment by michaelspellacy** [comment]
I think we are all well versed here on pitfalls of browser detection. Browsers more stable now, so it is mostly a non-issue. Feature detection is always the way to go.
