### ISSUE TITLE
Page Weight

### ISSUE THREAD

**Issue by michaelspellacy** [tmpworldwide/tmpworldwide.github.io#23]
Think it's time to up the page weight goal.  I see most pages hovering around 1MB so that, or lower, is probably more realistic number to strive for. We could say 1MB, but I want us to at least try to strive for something lower whenever possible. 

Cumulative Page Weight: ~750 - 950 KB

Thoughts?

**Comment by lenawan** [comment]
I think that's a practical number. The tb system has basic weight around
300KB.

tb-core 146.13 KB html 125.88 KB form 44.52 KB full.css 15.69 KB full.js
6.38 KB _Subtotal:_ _338.6_ KB
We can manage the other elements under 400KB.

**Comment by Brockenstein** [comment]
I don't think we should go over 950KB ever. I understand that the average is almost 2MBs for the internet now but we want to be better than the average.

**Comment by lenawan** [comment]
You are right, there is no need that much. I thing close to 600KB or 750KB
is good.

**Comment by Brockenstein** [comment]
~750 - 950 KB is fine with me I was just stating that 950KB should truly be our max and if we are hitting 1mb we should be questioning the design or features of the site.

**Comment by michaelspellacy** [comment]
I agree, @Brockenstein. Okay, will up the number then. Thanks for the feedback, all!

**Comment by michaelspellacy** [comment]
Updated. Closing.
