### ISSUE TITLE
Breakpoint Mixins

### ISSUE THREAD

**Issue by Brockenstein** [tmpworldwide/tmpworldwide.github.io#25]
When it comes to a mixin it should be robust and simple to call.

This one below is super simple to use.

```
$device_widths: (100px, 200px, 300px, 400px, 500px, 600px, 700px, 800px, 900px, 1000px, 1100px, 1200px, 1300px, 1400px);

@mixin bp($i){
    @media only screen and (min-width: (nth($device_widths, $i))) {
        @content;
    }
}
```

You then call it like so:

```
@include bp(10) {
      //styles
}
```

which would output

```
@media only screen and (min-width: 1000px) {
   //styles
}
```

I would prefer a more robust mixin like https://github.com/zellwk/mappy-breakpoints though I prefer the calls to be shorter so I would need to tweak that mappy one.. I know Max was been working on one. This is what he had below:

```
@mixin bp($queries, $type: only screen) {
  $query-count: length($queries);
  $media-statement: "#{$type} and";
  @for $i from 1 through $query-count {
    $query: nth($queries, $i);
    $value: '';
    $key: '';
    @if length($query) == 1 or nth($query, 2) == up {
      $key: min-width;
      $value: if(map-has-key($bp, nth($query, 1)), px-em(map-get($bp, nth($query, 1))), px-em(nth($query, 1)));
    } @else {
      @if nth($query, 2) == down {
        $key: max-width;
        $value: if(map-has-key($bp, nth($query, 1)), px-em(map-get($bp, nth($query, 1)) - 1), px-em(nth($query, 1) - 1));
      } @else {
        $key: nth($query, 1);
        $value: nth($query, 2);
      }
    }
    $media-statement: if($i == 1, "#{$media-statement} (#{$key}: #{$value})", "#{$media-statement}, (#{$key}: #{$value})");
  }
  @media #{$media-statement} {
    @content;
  }
}

@function px-em($px, $px-context: 16) {
  // Make sure it's a number
  @if(round($px)) {
    @return #{$px / $px-context}em;
  }
}

//Breakpoints for mixin, can be changed to whatever the dev wants
$bp: (
  S: 320,
  M: 768,
  L: 960
);

```

which you could call like

```
@include bp(L) {
  //styles
}
```

Max's should also allow you to do max width if need be, but I am not exactly sure. I haven't tested it much.

**Comment by stephendelancey** [comment]
I like the first one basically what I use just cleaner

**Comment by Brockenstein** [comment]
@stephendelancey we could merge the two so that the variables in the first one could be use in the more robust second one if someone wanted. I would like to see this just because every once in a while to fix an issue its easier to do max-width or even a range width.

**Comment by michaelspellacy** [comment]
I dig this.

**Comment by Brockenstein** [comment]
@michaelspellacy I am recommending that we have a couple of devs test https://github.com/zellwk/mappy-breakpoints I am using it now and loving it. I only wish I could change it from `@include mappy-bp` to `@include bp` but it crashes my compiler when I try to change it.

**Comment by michaelspellacy** [comment]
@Brockenstein What is our standard way of handling breakpoints these days?

**Comment by michaelspellacy** [comment]
@Brockenstein Nevermind, going to close this. We can continue conversation in Issue#24
