### ISSUE TITLE
Image Implementation

### ISSUE THREAD

**Issue by michaelspellacy** [tmpworldwide/tmpworldwide.github.io#27]
Gang,

We all know that images contribute to most of a page’s overall weight (up to 70%). While we all should be optimizing our images as much as possible, I was just wondering what common techniques you may be using to implement inline images (img)? Bit of an open discussion right now, but the hope is to take common design scenarios (like those huge banners) and try to ensure we are all using the same technique when implementing them, etc.

**Comment by michaelspellacy** [comment]
Let me be a tad more specific. In regard to inline images (not CSS backgrounds), do you use a single image and scale it? Do you use new `<picture>` element, etc. Just wondering what most common techniques are, etc.

**Comment by michaelspellacy** [comment]
Going to list some common scenarios I come across here. Will update as I find 'em:

## The Ghost Image

`<div class="banner"></div>`

```
.banner {
padding: 0 0 27.8% 0;
background: url(../v1_0/img/walt-disney-world-banner-large.jpg) no-repeat;
}
```

## Pros and Cons

Pros: 

Great for performance in that you can load in different images.

Cons: 

Setting percentage or other value to padding is complex. 
Managing multiple breakpoints also complex (maintenance can be difficult)
Depending on the context/image, bad for accessibility (in that you are not providing an equal experience)

## The Double Whammy

`<img src="mg/header-home-page.jpg" alt="" class="desk">`
`<img src="header-home-page-mobile.jpg" alt="" class="mob">`

## Pros and Cons

Pros: None

Cons: 

While easier to update, you could create a double performance hit.
if CSS not present (display: none), you present two images to a user. Visually (and auditory for screen readers)

**Comment by scampbell44** [comment]
I find the polyfill 'picturefill' and the html5 <picture> element  very easy to work with, fully responsive and cross browser consistent.

The element: 

```
<picture>
    <source media="(min-width:28.75em)" srcset="@Html.AssetUrl("v2_0/img/banner-job-matching.jpg")">
    <img src="@Html.AssetUrl("v2_0/img/banner-job-matching-sm.jpg")" alt="">
</picture>

```

With the following at bottom of theme.

```
<!-- PictureFill polyfill -->
  <script>
        document.createElement( "picture" );
  </script>
  <script src="@Html.AssetUrl("v2_0/js/picturefill.min.js")" async></script>
```

**Comment by michaelspellacy** [comment]
@scampbell44  I also prefer this method and believe we should be using it as much as possible moving forward. There are some things to keep in mind about it, though. Jason Grigsby has some great things to say about each use case that you should all check out:

http://blog.cloudfour.com/dont-use-picture-most-of-the-time/

In a nutshell, only use `<picture>` in instances where art direction is a requirement. For example, on our Boeing careers site, we have an instance where two very different images are being used. This is not a case where images are identical, but simply scaled down and used with different breakpoints:

https://tbcdn.talentbrew.com/company/185/v1_0/img/header-home-page.jpg
https://tbcdn.talentbrew.com/company/185/v1_0/img/header-home-page-mobile.jpg 

Perfect uses case for `<picture>` element.

In scenarios where images are _identical_, but scaled down to conserve bandwidth, as mentioned above, `srcset` and `sizes` are the way to go. On our corporate site, we have the following two images:

https://tbcdn.talentbrew.com/company/3401/v1_0/img/workinghere/career/banner-copywriter-sm.jpg
https://tbcdn.talentbrew.com/company/3401/v1_0/img/workinghere/career/banner-copywriter-lg.jpg

Here is the code:

```
<img src="https://tbcdn.talentbrew.com/company/3401/v1_0/img/workinghere/career/banner-copywriter-sm.jpg" srcset="https://tbcdn.talentbrew.com/company/3401/v1_0/img/workinghere/career/banner-copywriter-sm.jpg 982w, https://tbcdn.talentbrew.com/company/3401/v1_0/img/workinghere/career/banner-copywriter-lg.jpg 2000w" alt="">
```

You must "unlearn what you have learned" regarding responsive and images here. It is a  more adaptive solution. With srcset, we _suggest_ which images for the browser to use and the browser then makes the best choice it can based on various conditions of the viewing enviornment. Browsers are even smart enough to choose the best image based on bandwidth speed. How cool is that? I'm willing to bet that most design scenarios we encounter would fall under our team using srcset instead of picture. 

## Support

http://caniuse.com/#feat=srcset
http://caniuse.com/#feat=picture

As for as the polyfill , we are nearly at a point where we can drop it. On tmp.com, I opted to not use it, as the fallback image, https://tbcdn.talentbrew.com/company/3401/v1_0/img/workinghere/career/banner-copywriter-sm.jpg. was adequate enough for IE11 and Opera Mini users. I would only use in cases where it was a necessity, so if you think you can get away with using fallback only, then definitely go for it. :-)

**Comment by michaelspellacy** [comment]
In regards to banners we all love to hate, I think smart use of more current techniques and new standards  can help out here, but the problem is two-fold in that we seem to be overly concerned about the size of them in regards to screen real-estate and the fact that they obscure content below, etc. Personally, I think users will scroll if they need to and it's not _that_ big a deal, but I understand the concern some folks have. I can see issue from a creative perspective as well in that they see it as an opportunity to sell the brand (and not everybody begins at the home page), but I suspect that many of our designers also need to stop designing for one scenario (the one they see on their 27" Thunderbolt displays) and compromise here and help work towards solutions. Perhaps we meet somewhere in the middle and treat such things as enhancements on displays that can handle them. Only load very large banners in higher resolutions and smaller ones (or none at all) in lower. it's also not lost on me that time is biggest issue here in us working together to solve thorny design issues. I keep saying three weeks or so is not enough time to build great sites that work really well across a wide spectrum of device sizes. :-)

**Comment by michaelspellacy** [comment]
So, it's been almost two weeks since my last post. I move to make using more modern techniques, like using <picture> and srcset more of a standard. I don't think we need to include it in our main standards document (I'll look again to see if it makes sense to add), but this is something we should definitely be calling attention to in our code reviews. What say ya?

**Comment by Brockenstein** [comment]
Honestly, I think that article confused me more. As far as I can see the point of using picture is if the image is different. And img srcset is only if the resolution is different. For my current site it's sorta both. Both of these options have issues with ie11 and below. What I plan on doing is testing both See if one place better with ie11 or not. I will have my fallback as the large screen version of the image because IE11 isn't used on mobile.

**Comment by Brockenstein** [comment]
@michaelspellacy So in my case picture was exactly what I needed. I didn't need a polyfill because what I did was I had the main image as the large version which makes it a fallback for ie11 and below. ie11 and blow never need to load the small screen size layout of the image. But for the browsers supporting picture, they don't download the large image if its a small screen instead it only downloads the correct file, and even better on screen resize it will download the bigger one if needed. 

A lot of times when I see someone has done 

```
<img src="mg/header-home-page.jpg" alt="" class="desk">
<img src="header-home-page-mobile.jpg" alt="" class="mob">
```

Its because the layout is differnt so I would suggest going with picture.

**Comment by michaelspellacy** [comment]
Right, the main idea is to rely on picture/srcset moving forward instead of the hacks above. Yes, those are exactly the use cases for each. Picture for art direction and srcset for everything else :-) Yup, you could use larger image for fallback, but be careful doing so. The amount of mobile browsers that don't support it is likely greater than singular IE11, so mobile users are going to receive bigger payload. Mobile first, as always. :-)

**Comment by michaelspellacy** [comment]
I think most of us are using <picture> now, without issue, so, closing this.
