### ISSUE TITLE
Testing site speed in Google Page Insights

### ISSUE THREAD

**Issue by mhartz** [tmpworldwide/tmpworldwide.github.io#5]
Proposed addition to standards:
Loading time is a major contributing factor to page abandonment. So after completion of a site, each front-end developer should test their site Using the Google Devlopers PageSpeed Insights web application located at https://developers.google.com/speed/pagespeed/insights/. It is as easy as copying and pasting the URL into the text field.

Our desired score should be anything above 70/100, however our absolute lowest score should not fall below 60/100 on both mobile and desktop tests.

While it might not be possible to always achieve a perfect or near-perfect score, we should strive for a site that has the best possible score while maintaining the client requirements. Some issues might be out of our control as front-end developers, but we can take other precautions in order to develop the most efficient site possible.

---

Issues:
TB2.0 does not allow developer to test the site since it requires a login. So the tool only tests the login page. There is a Chrome Extension that also exists but does not give a metric score. Any other suggestions?

**Comment by michaelspellacy** [comment]
Thinking...

**Comment by mhartz** [comment]
This issue has been stagnant for awhile - anyone have any input? Are you ok with the proposed metric scores? The other issue that it might not work for us currently shouldn't be a concern since these should be basic standards for all code.

**Comment by mhartz** [comment]
Actually I am going to close it since it is also listed in issue #10 which seems to be more popular.
