### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by michaelspellacy** [tmpworldwide/tmpworldwide.github.io#8]
Do we want to include best practices for interface elements, like carousels, in the standards doic or keep it separate? Right now I'm thinking that patterns should reside in a different document as to not taint our core principles and standards. Thoughts?

**Comment by dgreen007** [comment]
I agree in keeping those items separated from core.

**Comment by scampbell44** [comment]
My vote is for separation.
Sherrie

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by mhartz** [comment]
I don't think we should add them into the normal standards, but in a separate doc would be ok. The idea would be that if the standards are followed in general, the elements like carousels should already follow the core principles.

**Comment by michaelspellacy** [comment]
@JakeRuef is working on something internally that might fit into this. We'll see where that goes.

**Comment by JakeRuef** [comment]
Currently we are hustling to complete the section containing rules/guides/UXthoughts for TB2.0 stuff, but eventually we will add more and more information to the site that will help give guidance about everything from how to set up your outlook to best practices for the web. 

That being said, if you guys have a list of comonly seen "bad habits" that always get flagged or cause issues (i know i have one) then I would be more than greatful if you guys started gathering that info and creating the argument or explination as to why TMP's stance is that way. Then i could add them to the sections carved out for that type of information. This way we may be able to have that info up earlier than if we waited until I got to it. lol

In an ideal world...There will be a point this year that we will be able to say...

"hey this isnt a good practice and TMP does not recomend this. Check this out: www.heres-the-info-I-usually-have-to-type-three-times-a-week.com"

**Comment by michaelspellacy** [comment]
> > Check this out: www.heres-the-info-I-usually-have-to-type-three-times-a-week.com"

I blog for this very reason. Well, partially. Why bury something in an email when I can share with the world. :-)

Noted.

**Comment by michaelspellacy** [comment]
p.s. I should register that domain.

**Comment by michaelspellacy** [comment]
@tmpworldwide/ui-ux-developers-designers  We have been including patterns in https://tmpworldwide.github.io/tmp-resource-library/ .If you would would like to contribute a UI technique you use often in your own work, then let's include it! The only rule for inclusion is that it be accessible (I can help you there). The more we can build this library up, the easier our development lives will be. Hopefully!
